### ISSUE TITLE
How do I use this in my Xposed project?

### ISSUE THREAD

**Issue by b1bradders** [libxposed/helper#4]
I see `findAndHookMethod` in a Xposed-module tutorial on GitHub ([this][tut] one), but when I build `libxposed/helper` and put it into my project, I can't seem to find any `findAndHookMethod`? I would use `hook()` but I'm not sure how it works.

Any support? Thanks in advance.

[tut]: https://github.com/rovo89/XposedBridge/wiki/Development-tutorial

**Comment by yujincheng08** [comment]
It's not finished.

**Comment by b1bradders** [comment]
Oh I see. Thanks for the suprisingly fast response 😨
